export const POKEDEX_LIST_INIT = '[POKEDEX] POKEDEX_LIST_INIT';
export const POKEDEX_LIST_SUCCESS = '[POKEDEX] POKEDEX_LIST_SUCCESS';
export const POKEDEX_LIST_ERROR = '[POKEDEX] POKEDEX_LIST_ERROR';
export const POKEDEX_SELECTED = '[POKEDEX] POKEDEX_SELECTED';
export const POKEDEX_SELECTED_INIT = '[POKEDEX] POKEDEX_SELECTED_INIT';
export const POKEDEX_SELECTED_SUCCESS = '[POKEDEX] POKEDEX_SELECTED_SUCCESS';
export const POKEDEX_SELECTED_ERROR = '[POKEDEX] POKEDEX_SELECTED_ERROR';
