export const LOGIN_INIT = '[LOGIN] LOGIN_INIT';
export const LOGIN_SUCCESS = '[LOGIN] LOGIN_SUCCESS';
export const LOGIN_ERROR = '[LOGIN] LOGIN_ERROR';
export const LOGIN_TERMINATE = '[LOGIN] LOGIN_TERMINATE';
