export const COACH_LIST_INIT = '[COACH] COACH_LIST_INIT';
export const COACH_LIST_SUCCESS = '[COACH] COACH_LIST_SUCCESS';
export const COACH_LIST_ERROR = '[COACH] COACH_LIST_ERROR';
export const COACH_CREATE_INIT = '[COACH] COACH_CREATE_INIT';
export const COACH_CREATE_SUCCESS = '[COACH] COACH_CREATE_SUCCESS';
export const COACH_CREATE_ERROR = '[COACH] COACH_CREATE_ERROR';
export const COACH_SELECTED = '[COACH] COACH_SELECTED';
